version: '3.5'
networks:
    kafka:
      name: rmoff_kafka
      external: True
services:
  prometheus:
    image: prom/prometheus:v2.47.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks: 
      - kafka
  alertmanager:
    image: prom/alertmanager:v0.26.0
    ports:
      - "19093:9093"
    networks: 
      - kafka
  grafana:
    image: grafana/grafana:5.2.1
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks: 
      - kafka  
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zookeeper
    networks: 
      - kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      EXTRA_ARGS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.20.0.jar=9200:/usr/share/jmx_exporter/zookeeper.yml

    restart: always   
    volumes:
      - ./jmx-exporter:/usr/share/jmx_exporter/
  

  broker:
    image: confluentinc/cp-kafka:5.5.0
    container_name: broker
    networks: 
      - kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.20.0.jar=9200:/usr/share/jmx_exporter/kafka-broker.yml
    volumes:
      - ./jmx-exporter:/usr/share/jmx_exporter/
    restart: always
volumes:
  grafana-data:    