global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

rule_files: ["rules/*.yml"]

alerting:
  alertmanagers:
    - timeout: "10s"
      scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]
scrape_configs:        
  - job_name: nifi
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics

    scheme: http
    static_configs:
      - targets: ["nifi:9090"]

  
  