version: '3.5'
networks:
    kafka:
      name: rmoff_kafka
      external: True
services: 
 cas: 
    container_name: cas1
    image: cassandra:latest
    volumes:
      - ./node1_cassandra:/var/lib/cassandra/data
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
    networks: 
      - kafka  