version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    # 8.x
    environment: ['CLI_JAVA_OPTS=-Xms2g -Xmx2g','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']
    ports:
      - 9200:9200
    networks:
      - kafka
    volumes:
      - esdata1:/usr/share/elasticsearch/data  
    ulimits:
      memlock:
        soft: -1
        hard: -1
      
    

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    environment:
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
    ports:
      - 5601:5601
    networks:
      - kafka
    
  elasticsearch_exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    command:
     - '--es.uri=http://elasticsearch:9200'
    restart: always
    ports:
    - "9114:9114" 
    networks:
      - kafka         

networks:
    kafka:
      name: rmoff_kafka
      external: True
      
volumes:
  esdata1:
    driver: local      